version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
      runas: root
